# Your Wi-Fi SSID and password
wifi_ssid: "<your ssid>"
wifi_password: "<your password>"
fallback_wifi_ssid: "<your fallback ssid>"
fallback_wifi_password: "<your fallback password>"
ota_password: "<your ota password>"